server:
  port: 8080

spring:
#---------------------kafka配置---------------------
#---------------------数据源---------------------
  datasource:
    druid:
      quartz:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
        username: wyc
        password: 1111
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          initial-size: 20
          min-idle: 5
          max-active: 50
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
      demo:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
        username: wyc
        password: 1111
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          initial-size: 20
          min-idle: 5
          max-active: 50
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

#---------------------mybatis---------------------
mybatis:
  credit:
    mapper-locations: classpath:mappers/demo/*.xml
  quartz:
    mapper-locations: classpath:mappers/quartz/*.xml

#---------------------日志---------------------
logging:
  level:
    root: info


